name: Process Outline Request

on:
  repository_dispatch:
    types: [outline-request]

jobs:
  process-outline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios openai@3.3.0

      - name: Process outline request
        id: process
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REQUEST_DATA: ${{ toJson(github.event.client_payload) }}
        run: |
          node .github/scripts/process-outline.js

      - name: Return response
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: outline-response
          client-payload: ${{ steps.process.outputs.response }}
